#!/bin/bash

export PATH="/usr/local/bin:$PATH"

# already done
#gsl -q -script:empty_c zmon.xml
#gsl -q -script:empty_c zsuper.xml
#gsl -q -script:empty_c zmon_api.xml


gsl -q -script:project.gsl project.xml
